PyTorch/Segmentation/MaskRCNN/README.md
PyTorch/Segmentation/MaskRCNN/pytorch/Dockerfile
PyTorch/Segmentation/MaskRCNN/pytorch/scripts/docker/interactive.sh
PyTorch/Segmentation/MaskRCNN/pytorch/scripts/inference.sh
PyTorch/Segmentation/MaskRCNN/pytorch/scripts/inference_benchmark.sh

fix CD path in readme
fix mkdir command in dockerfile
Remove trailing space in interactive.sh
inference scripts for 1 GPU

Fix README and Dockerfile

---

TensorFlow/LanguageModeling/BERT/README.md

fixing model path mentioned in readme

fix readme

---

README.md

Add a list all currently supported models to help users find and navigate quickly to the appropriate model.

Add current models to README

---

TensorFlow/LanguageModeling/BERT/run_pretraining.py

Mismatch in cl arguments spelling as pointed out by @vlarine

fix mismatch in cl arguments for BERT

---

hubconf.py

changes only in hubconf.py, affecting no other code.

ssd exposure via hubconf.py (together with ssd utils)

---

PyTorch/Classification/RN50v1.5/README.md
PyTorch/Classification/RN50v1.5/image_classification/dataloaders.py

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

Fix typo in RN50 PyTorch readme, remove unneeded lines for DALI

---

PyTorch/LanguageModeling/BERT/scripts/docker/build.sh
PyTorch/LanguageModeling/BERT/scripts/docker/launch.sh

fix pytorch bert docker build.sh and launch.sh

Yzhang123 patch 1

---

hubconf.py

The colab error was caused by downloading file to non-existent dir ;) . Creating dir should fix it.

Fix urllib error on colab hub example

---

PyTorch/Translation/GNMT/train.py

[GNMT PyT] Fix for fp16 training w/o label smoothing

---

PyTorch/Segmentation/MaskRCNN/pytorch/docker/Dockerfile
PyTorch/Segmentation/MaskRCNN/pytorch/docker/docker-jupyter/Dockerfile

This repo itself should also be included in the docker build, ready to be used for demos.

add this repo to docker build

---

PyTorch/SpeechSynthesis/Tacotron2/trt/README.md

Signed-off-by: Rajeev Rao <rajeevrao@nvidia.com>

Minor README cleanup for TRT Tacotron2 example

---

PyTorch/LanguageModeling/BERT/README.md
TensorFlow/LanguageModeling/BERT/README.md

Providing more information about the LAMB optimizer implementation

Updating BERT Readme Docs

---

.gitmodules
TensorFlow/LanguageModeling/BERT/Dockerfile

1. remove trtis submodule
2. download from https://github.com/NVIDIA/tensorrt-inference-server/releases
#352 cleaned up

trtis dependency fix

---

TensorFlow/Segmentation/VNet/Dockerfile
TensorFlow/Segmentation/VNet/hooks/profiling_hook.py
TensorFlow/Segmentation/VNet/hooks/train_hook.py
TensorFlow/Segmentation/VNet/main.py
TensorFlow/Segmentation/VNet/requirements.txt
TensorFlow/Segmentation/VNet/utils/model_fn.py

[x] Skip checkpointing during benchmarking to reduce variance
[x] Improve the freedback from the application when benchmarking

Vnet benchmark fix

---

PyTorch/LanguageModeling/BERT/run_glue.py
PyTorch/LanguageModeling/BERT/scripts/run_glue.sh

Glue(MRPC) fine-tuning with LAMB pretrained checkpoint

Sharathts patch 2

---

PyTorch/SpeechRecognition/Jasper/trt/Dockerfile
PyTorch/SpeechRecognition/Jasper/trt/README.md
PyTorch/SpeechRecognition/Jasper/trt/perf.py
PyTorch/SpeechRecognition/Jasper/trt/perfutils.py
PyTorch/SpeechRecognition/Jasper/trt/scripts/trt_inference_benchmark.sh
PyTorch/SpeechRecognition/Jasper/trt/trtutils.py
PyTorch/SpeechRecognition/Jasper/trtis/scripts/export_model_helper.sh

-freeze onnx-trt version for stability in trt/Dockerfile
-fixed object type conversion
-set onnx dynamic shape to default

Jasper TRT Fix

---

TensorFlow/Segmentation/VNet/main.py

Signed-off-by: Pablo Ribalta <pribalta@nvidia.com>

Enable rewrite for inference

---

TensorFlow/Segmentation/UNet_Medical/requirements.txt
TensorFlow2/Segmentation/UNet_Medical/requirements.txt

Signed-off-by: Pablo Ribalta Lorenzo <pribalta@nvidia.com>

Fix requirements for UNet Medical

---

PyTorch/SpeechSynthesis/Tacotron2/README.md
PyTorch/SpeechSynthesis/Tacotron2/run_latency_tests_cpu.sh

changed Readme and run_latency_tests_cpu.sh

add Intel optimization for PyTorch

---

TensorFlow2/Segmentation/UNet_Medical/utils/losses.py

As per https://github.com/NVIDIA/DeepLearningExamples/issues/468

Replace softmax_cross_entropy_with_logits with binary_crossentropy

---

PyTorch/SpeechSynthesis/Tacotron2/inference.py
PyTorch/SpeechSynthesis/Tacotron2/test_infer.py

Don't move input vectors to GPU in case we've set --cpu-run

Tacotron2 --cpu-run fix

---

hubconf.py

Resolves https://github.com/NVIDIA/DeepLearningExamples/issues/508

[SSD][hubconf] contiguous input tensor

---

TensorFlow2/Segmentation/MaskRCNN/download_and_process_pretrained_weights.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/benchmark_inference.py
TensorFlow2/Segmentation/MaskRCNN/scripts/benchmark_training.py
TensorFlow2/Segmentation/MaskRCNN/scripts/train_1GPU.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/train_4GPU.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/train_8GPU.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/train_AMP_1GPU.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/train_AMP_4GPU.sh
TensorFlow2/Segmentation/MaskRCNN/scripts/train_AMP_8GPU.sh
TensorFlow2/Segmentation/MaskRCNN/weights/extract_RN50_weights.py

* Update to new TPU checkpoint
* Update path to checkpoint in scripts
Signed-off-by: Pablo Ribalta <pribalta@nvidia.com>

Update checkpoint MaskRCNN

---

TensorFlow/Segmentation/UNet_Industrial/README.md

Signed-off-by: Pablo Ribalta Lorenzo <pribalta@nvidia.com>
Solves: https://github.com/NVIDIA/DeepLearningExamples/issues/669

[UNetInd] Add --gpus flag to docker run

---

PyTorch/Classification/ConvNets/triton/deployer.py
TensorFlow/Classification/ConvNets/utils/cmdline_helper.py

- Fix for duplicated command line arguments in ConvNets/TF
- Fix loading checkpoint twice in triton deployment for ConvNets/PyT

Minor fixes in ConvNets

---

TensorFlow/LanguageModeling/BERT/triton/README.md

Include pointer to TensorRT perf numbers in triton readme for BERT

Triton README

---

README.md

Adding DLC and Glossary to main README

Adding DLC to main README

---

FasterTransformer/v1/fastertransformer/common.h
FasterTransformer/v1/fastertransformer/trt_plugin/trt_model.h

The two serious bugs will make compilation failed.

fix two obvious bugs in Faster Transformers v1.

---

PyTorch/LanguageModeling/BERT/data/WikiDownloader.py
TensorFlow/LanguageModeling/BERT/data/WikiDownloader.py

Mirror speedup download by 10x
wget fixes the stall with urllib

Use mirror and wget

---

TensorFlow/LanguageModeling/BERT/Dockerfile

pynvml missing in Dockerfile which throws errors later. Added pynvml to handle this issue.

pynvml added to Dockerfile

---

TensorFlow/Classification/ConvNets/resnet50v1.5/README.md
TensorFlow/Classification/ConvNets/resnext101-32x4d/README.md
TensorFlow/Classification/ConvNets/se-resnext101-32x4d/README.md

Document behavior when --num_iter < --warmup_steps

---

TensorFlow/Classification/ConvNets/model/resnet.py

Removed duplicated lines (probably merge issue)
Fixed squeezing that results in wrong shapes later in the graph when BS=1

Fixed wrong shapes with BS=1

---

PyTorch/Segmentation/nnUNet/README.md

Signed-off-by: Pablo Ribalta Lorenzo <pribalta@nvidia.com>

nnUNet: Add reference to PyTorch Lightning to readme

---

PyTorch/LanguageModeling/Transformer-XL/pytorch/eval.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/inference/mem_transformer_jit.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/mem_transformer.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/scripts/inference_benchmark.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/train.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/utils/exp_utils.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/utils/gpu_affinity.py

* WAR for issues with logging in distributed setting
* improved CPU-GPU affinity
* minor optimizations for the model

[TXL/PyT] Update for PyT Transformer-XL:

---

TensorFlow/Segmentation/UNet_Industrial/README.md

Signed-off-by: Pablo Ribalta Lorenzo <pribalta@nvidia.com>

Fix number of gpus in UNet ind readme

---

TensorFlow2/Classification/ConvNets/efficientnet/README.md

Training time for V100 8GPUs and 32GPUs were swapped, corrected it.

Update training time typo

---

PyTorch/SpeechRecognition/Jasper/Dockerfile
PyTorch/SpeechRecognition/Jasper/common/dali/pipeline.py
PyTorch/SpeechRecognition/Jasper/common/features.py
PyTorch/SpeechRecognition/Jasper/train.py

Fixes pyprof import on 21.xx-py3 containers, removes DALI warnings.

[Jasper/PyT] Fix pyprof import

---

PyTorch/SpeechRecognition/Jasper/common/dali/data_loader.py
PyTorch/SpeechRecognition/Jasper/common/dali/iterator.py
PyTorch/SpeechRecognition/Jasper/common/dali/pipeline.py

Updates DALI implementation for Jasper, to follow the new functional API, which is the recommended one.
Signed-off-by: Joaquin Anton <janton@nvidia.com>

Update DALI Jasper pipeline to functional API

---

PyTorch/LanguageModeling/Transformer-XL/README.md
PyTorch/LanguageModeling/Transformer-XL/pytorch/inference/mem_transformer_jit.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/inference/proj_adaptive_softmax_jit.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/mem_transformer.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_enwik8_base.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_enwik8_large.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_lm1b_base.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_lm1b_large.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_multinode_wt103_large.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_text8_base.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_text8_large.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_wt103_base.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/run_wt103_large.sh
PyTorch/LanguageModeling/Transformer-XL/pytorch/train.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/utils/log_uniform_sampler.py
PyTorch/LanguageModeling/Transformer-XL/pytorch/utils/proj_adaptive_softmax.py

* changed API calls to torch.einsum
* added export OMP_NUM_THREADS=1 to all launcher scripts
* additional runtime checks to ensure that launch configuration is valid

[TXL/PyT] update:

---

PyTorch/SpeechSynthesis/README.md

Spectrograms are acoustic features rather than linguistic features.

Fix typo in speech synthesis readme

---

PyTorch/Detection/SSD/Dockerfile

Move to cuDNN 8.22 to pick up an oddity with APM and small batch size in training SSD

Update Dockerfile to use PyTorch 21.07 as base
