- TensorFlow/LanguageModeling/BERT/README.md
Small fix to change "Bert" to "BERT" in the README title
> Typo/stylistic fix for BERT README title

- TensorFlow/LanguageModeling/BERT/run_pretraining.py
`FLAGS.save_checkpoint_steps` naming is inconsistent in the [run_pretraining.py](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/run_pretraining.py) and [run_pretraining.sh](https://github.com/NVIDIA/DeepLearningExamples/blob/master/TensorFlow/LanguageModeling/BERT/scripts/run_pretraining.sh) causing an error.
> Fix FLAG.save_checkpoint_steps naming inconsistency.

- TensorFlow/Detection/SSD/download_all.sh
In response to issue #102 
Without this change, SSD training is terminated with error:
```
tensorflow.python.framework.errors_impl.DataLossError: corrupted record at 0
[[{{node IteratorGetNext}}]]
[[{{node IteratorGetNext}}]]
```
because the dataset prepared by `download_all.sh` script is invalid.
> [TensorFlow/Detection/SSD][issue #102] use dataset preprocessing script from tensorflow/object_detection

- TensorFlow/docs/amp/notebook_v1.14/auto_mixed_precision_demo_cifar10.ipynb
Here is a simple demo notebook to show Automatic Mixed Precision (AMP) working on image classification on CNN in TensorFlow 1.14.
The notebook in my fork can be opened in Colab using the following link: https://colab.research.google.com/github/tlkh/DeepLearningExamples/blob/master/TensorFlow/docs/amp/notebook_v1.14/auto_mixed_precision_demo_cifar10.ipynb
This notebook will also be used in conjunction with this TensorFlow PR to the docstring for `tf.train.experimental.enable_mixed_precision_graph_rewrite`: https://github.com/tensorflow/tensorflow/pull/29249
> Added demo notebook for AMP (image classification)

- PyTorch/Segmentation/MaskRCNN/pytorch/docker/Dockerfile
Simply include jupyter in this docker image, so we don't need to build a separate docker image just for jupyter
> Include jupyter in this docker build

- PyTorch/Translation/Transformer/train.py
In train.py, line 391: predictions = [hypo[1] + ('\n' if hypo[-1]!='\n' else '') for hypo in predictions], I think it should be predictions = [hypo[1] + ('\n' if hypo[1][-1]!='\n' else '') for hypo in predictions] because hypo[-1] is a whole sentence which will never be "\n" at all.
> Fix the Validation in Transformer

- PyTorch/SpeechSynthesis/Tacotron2/train.py
I noticed that the loss of the last validation batch was logged instead of the average across all batches.
> Fixed wrong val loss being logged

- TensorFlow/LanguageModeling/BERT/run_pretraining.py
Changed run_pretraining.py to not require `--eval_files_dir` if not doing eval.
> Fix `eval_files_dir` requirement.

- hubconf.py
The PyTorch SSD implemented by NVIDIA relies on the nvidia_ssd_processing_utils() routines in this module
(see https://pytorch.org/hub/nvidia_deeplearningexamples_ssd/).
Python 3 has issues accessing skimage's io and transform in the original code (issue reported in issue https://github.com/pytorch/hub/issues/77).
> Fix skimage import issue, for NVIDIA's PyTorch SSD

- PyTorch/Recommendation/DLRM/dlrm/model.py
I executed following command.
```bash
python3 -m dlrm.scripts.main --mode train --max_steps 500 --benchmark_warmup_steps 250 --synthetic_dataset --print_freq 1
```
and got this error.
```bash
(...snip)
Traceback (most recent call last):
File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/root/DeepLearningExamples/PyTorch/Recommendation/DLRM/dlrm/scripts/main.py", line 509, in <module>
app.run(main)
File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 299, in run
_run_main(main, args)
File "/usr/local/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
sys.exit(main(argv))
File …
```
> Fix [PyT/DLRM] bug of model.py

- PyTorch/Segmentation/MaskRCNN/pytorch/notebooks/README.md
There was a typo in the command to start the docker container. 
The correct flag is `-it` for interactive terminal
> Typo in README instructions

- PyTorch/SpeechSynthesis/Tacotron2/inference.py
#491 
#496 
Same as the train.py, for inference.py, the 'get_model' function throws the invalid 'to_cuda' error. I have updated the argument.
Here is the info trace:
`Traceback (most recent call last):
File "inference.py", line 273, in <module>
main()
File "inference.py", line 206, in main
args.fp16, args.cpu, forward_is_infer=True)
File "inference.py", line 113, in load_and_setup_model
forward_is_infer=forward_is_infer)
TypeError: get_model() got an unexpected keyword argument 'to_cuda'`
> [Tacotron2] fixed get_model in inference.py

- TensorFlow/LanguageModeling/BERT/run_squad.py
This reduces Horovod overhead when XLA is enabled.
~7-9% speedup is observed for BERT Squad fp32 and ~3-4% speedup for fp16.
> Enable async_io for squad.

- TensorFlow/Classification/ConvNets/resnet50v1.5/README.md
- TensorFlow/Classification/ConvNets/resnext101-32x4d/README.md
- TensorFlow/Classification/ConvNets/se-resnext101-32x4d/README.md
Two changes to documentation:
- Inform an user that benchmark can use synthetic dataset if dataset path is omitted.
- Fix small naming issue with QuickStart Guide.
> [ConvNets/TF] Document synthetic dataset options

- PyTorch/LanguageModeling/BERT/run_pretraining.py
The data loader is never correctly loaded from a checkpoint because of this typo.
> [BERT/PyT] Fix dataloader typo

- PyTorch/Classification/ConvNets/classify.py
- PyTorch/Classification/ConvNets/main.py
Pytorch DDP model checkpoints contain "model." prefix.
This makes keys to mismatch during loading the checkpoint.
This fix removes the prefix if exists during load, allowing to use NGC checkpoints.
> [ConvNets/PyT] Fixed distributed checkpoint loading

- TensorFlow2/Segmentation/UNet_Medical/README.md
Adds info how to fix bugs such as https://github.com/NVIDIA/DeepLearningExamples/issues/679
```[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "main.py", line 69, in <module>
[1,0]<stderr>:    main()
[1,0]<stderr>:  File "main.py", line 57, in main
[1,0]<stderr>:    train(params, model, dataset, logger)
[1,0]<stderr>:  File "/workspace/unet/run.py", line 86, in train
[1,0]<stderr>:    train_step(images, labels, warmup_batch=iteration == 0)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 580, in __call__
[1,0]<stderr>:    result = self._call(*args, **kwds)
[1,0]<stderr>:  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/def_function.py", line 644, in _call
[1,0]<stderr>:    return …
```
> Add info about NCCL issue in 2.7.5 (20.06)

- PyTorch/SpeechSynthesis/Tacotron2/waveglow/model.py
in PyTorch 1.6 integer division will produce following Runtime error when converting Waveglow model to ONNX:
"Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in
Python 3. Use true_divide or floor_divide (// in Python) instead."); ''
Change the division to floor division to allow export of Waveglow in PyTorch 1.6.
> Fix integer division in Waveglow

- TensorFlow/LanguageModeling/BERT/README.md
update has been made for Throughput- mixed precision number (8 GPUs)
updates.
-table columns for weak scaling were swapped. Fixed
> updated Fine-tuning training performance table numbers for DGX A100

- FasterTransformer/v3.1/bert-quantization/bert-pyt-quantization/data/GLUEDownloader.py
- PyTorch/LanguageModeling/BERT/data/GLUEDownloader.py
- TensorFlow/LanguageModeling/BERT/data/GLUEDownloader.py
This PR fixes an issue, #854. Current URL is older version URL for `download_glue_data.py`, but recently the URLs for dataset have been updated. Therefore, it needs to be updated.
> Update URLs for GLUE downloader.

- FasterTransformer/v3.1/fastertransformer/common.h
There is a wrong data type in print_to_screen of common.h. The datatype of tmp should be same as result's.
> Fix the bug of mismatching datatype in print_to_screen

- PyTorch/SpeechRecognition/Jasper/requirements.txt
`pip` crashes upon `pyYAML` update attempt. Keep the stock version from the `20.10` container.
> [Jasper/PyT] Fix version of pyYAML==5.3.1 to prevent pip from crashing

- PyTorch/SpeechRecognition/Jasper/Dockerfile
- PyTorch/SpeechRecognition/Jasper/requirements.txt
Bump PyYAML through `conda` due to security vulnerabilites in PyYAML < 5.4.
> [Jasper/PyT] Update PyYAML

- TensorFlow/Classification/ConvNets/model/resnet.py
Fixed gradient calculation in new added distributed training signal handler. Null gradient was calculated leading to crash when mixing with AMP
> Fix gradient calculation for sync variable

- TensorFlow/Recommendation/NCF/ncf.py
Passing `hvd.rank()` into `DataGenerator`
https://github.com/NVIDIA/DeepLearningExamples/blob/ef98b2cef9dfdd3cf61f028bc5b33e7db48d49ec/TensorFlow/Recommendation/NCF/ncf.py#L230
```
data_generator = DataGenerator(
args.seed,
hvd.rank(),
nb_users,
...
```
will cause `cp.cuda.Device(self.hvd_rank).use()`
https://github.com/NVIDIA/DeepLearningExamples/blob/ef98b2cef9dfdd3cf61f028bc5b33e7db48d49ec/TensorFlow/Recommendation/NCF/input_pipeline.py#L91
```
self.hvd_rank = hvd_rank
cp.cuda.Device(self.hvd_rank).use()
```
set the wrong GPU index when using multiple nodes, leading to
```
cupy_backends.cuda.api.runtime.CUDARuntimeError: cudaErrorInvalidDevice: invalid device ordinal
```
replace `hvd.rank()` with `hvd.local_rank()`
> Set GPU index based on local_rank instead of rank

- PyTorch/LanguageModeling/BERT/data/GLUEDownloader.py
The linked GLUE downloader script has several issues which prevent it from downloading the MRPC components. Creating a new fork of the linked gist allows these items to be sorted out.
Also including a [link to my fork](https://gist.github.com/roclark/9ab385e980c5bdb9e15ecad5963848e0) of the gist which is able to complete successfully.
Fixes #929
Signed-Off-By: Robert Clark <roclark@nvidia.com>
> [BERT/PyT] Update GLUE Download Tool

- PyTorch/Translation/Transformer/train.py
Currently, `save_checkpoint`function decides whether the current epoch has reached the interval of saving checkpoints by:
```def save_checkpoint(args, trainer, epoch_itr, val_loss):
if epoch_itr.epoch % args.save_interval == 0:
return  # won't save anything
... # process & save
```
However, instead of skiping the saving process when `epoch_itr.epoch % args.save_interval == 0`, it should actually save the model here. In the worst case and the default case (`args.save_interval = 1`), the program won't save any checkpoints at all.
> Fix a logic flaw that causes checkpoints to be saved at wrong epochs in the transformer example.
